#' A data set created by merging 1) data from a "gold standard" survey and 2) data from
#' other surveys of the same universe. Data from the "gold standard" survey are assumed to
#' be the survey universe's "actual" response; data from the other surveys have survey
#' error which the functions in 'TSEind' can calculate. Data are organized by survey
#' (columns) and survey question (rows), and their values are the aggregate, "topline"
#' responses to the survey questions which can range from 1 to 99 (the scale used
#' by each survey question).
#'
#' @format A data frame with 10 rows and 6 variables
#' \describe{
#' \item{Q}{survey questions, numbered 1 through 10}
#' \item{A1, A2}{data from "gold standard" survey; A1 is the "actual" data for all 10
#' survey questions, A2 is the "actual" data for all survey questions except Q2 (in
#' function examples, A2 is paired with S3 which is missing data for Q2}
#' \item{S1, S2, S3}{data from other surveys; S3 is missing data for Q2}
#' }
#'
#' @source Example data generated by author
"TESTIND"
